OPTIONS SPOOL;
%let delim=%sysfunc(ifc(%eval(sysscp. = WIN),\,/));
%let vahost=vamaster;
%let folder=/opt/sas/datas/lasradm;
%let proxyhost="";
%let proxyport=0;
%let stopdate = %sysfunc(year(%sysfunc(today())));

libname essence "folder";

filename xmlmap "folder.&delim.PrixCarburants_annuel_xmlmap.map";
DATA _NULL_;
  FILE xmlmap dsd;
  PUT '<?xml version="1.0" encoding="UTF-8"?>
<!-- ############################################################ -->
<!-- 2014-12-18T17:09:39 -->
<!-- SAS XML Libname Engine Map -->
<!-- Generated by XML Mapper, 904000.0.0.20130522190000_v940 -->
<!-- ############################################################ -->
<!-- ###  Validation report                                   ### -->
<!-- ############################################################ -->
<!-- XMLMap validation completed successfully. -->
<!-- ############################################################ -->
<SXLEMAP name="AUTO_GEN" version="2.1">
    <NAMESPACES count="0"/>

    <!-- ############################################################ -->
    <TABLE description="pdv" name="pdv">
        <TABLE-PATH syntax="XPath">/pdv_liste/pdv</TABLE-PATH>

        <COLUMN class="ORDINAL" name="pdv_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="pdv_id">
            <PATH syntax="XPath">/pdv_liste/pdv/@id</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="pdv_latitude">
            <PATH syntax="XPath">/pdv_liste/pdv/@latitude</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="pdv_longitude">
            <PATH syntax="XPath">/pdv_liste/pdv/@longitude</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="pdv_cp">
            <PATH syntax="XPath">/pdv_liste/pdv/@cp</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="pdv_pop">
            <PATH syntax="XPath">/pdv_liste/pdv/@pop</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>1</LENGTH>
        </COLUMN>

        <COLUMN name="adresse">
            <PATH syntax="XPath">/pdv_liste/pdv/adresse</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>255</LENGTH>
        </COLUMN>

        <COLUMN name="ville">
            <PATH syntax="XPath">/pdv_liste/pdv/ville</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>255</LENGTH>
        </COLUMN>

        <COLUMN name="fermeture">
            <PATH syntax="XPath">/pdv_liste/pdv/fermeture</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>32</LENGTH>
        </COLUMN>

        <COLUMN name="rupture">
            <PATH syntax="XPath">/pdv_liste/pdv/rupture</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>32</LENGTH>
        </COLUMN>

    </TABLE>

    <!-- ############################################################ -->
    <TABLE description="ouverture" name="ouverture">
        <TABLE-PATH syntax="XPath">/pdv_liste/pdv/ouverture</TABLE-PATH>

        <COLUMN class="ORDINAL" name="pdv_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN class="ORDINAL" name="ouverture_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv/ouverture</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="ouverture_debut">
            <PATH syntax="XPath">/pdv_liste/pdv/ouverture/@debut</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>time</DATATYPE>
            <FORMAT width="8">IS8601TM</FORMAT>
            <INFORMAT width="8">IS8601TM</INFORMAT>
        </COLUMN>

        <COLUMN name="ouverture_fin">
            <PATH syntax="XPath">/pdv_liste/pdv/ouverture/@fin</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>time</DATATYPE>
            <FORMAT width="8">IS8601TM</FORMAT>
            <INFORMAT width="8">IS8601TM</INFORMAT>
        </COLUMN>

        <COLUMN name="ouverture_saufjour">
            <PATH syntax="XPath">/pdv_liste/pdv/ouverture/@saufjour</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>32</LENGTH>
        </COLUMN>

    </TABLE>

    <!-- ############################################################ -->
    <TABLE description="services" name="services">
        <TABLE-PATH syntax="XPath">/pdv_liste/pdv/services</TABLE-PATH>

        <COLUMN class="ORDINAL" name="pdv_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN class="ORDINAL" name="services_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv/services</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

    </TABLE>

    <!-- ############################################################ -->
    <TABLE description="service" name="service">
        <TABLE-PATH syntax="XPath">/pdv_liste/pdv/services/service</TABLE-PATH>

        <COLUMN class="ORDINAL" name="services_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv/services</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN class="ORDINAL" name="service_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv/services/service</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="service">
            <PATH syntax="XPath">/pdv_liste/pdv/services/service</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>23</LENGTH>
        </COLUMN>

    </TABLE>

    <!-- ############################################################ -->
    <TABLE description="prix" name="prix">
        <TABLE-PATH syntax="XPath">/pdv_liste/pdv/prix</TABLE-PATH>

        <COLUMN class="ORDINAL" name="pdv_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN class="ORDINAL" name="prix_ORDINAL">
            <INCREMENT-PATH beginend="BEGIN" syntax="XPath">/pdv_liste/pdv/prix</INCREMENT-PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="prix_nom">
            <PATH syntax="XPath">/pdv_liste/pdv/prix/@nom</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>6</LENGTH>
        </COLUMN>

        <COLUMN name="prix_id">
            <PATH syntax="XPath">/pdv_liste/pdv/prix/@id</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

        <COLUMN name="prix_maj">
            <PATH syntax="XPath">/pdv_liste/pdv/prix/@maj</PATH>
            <TYPE>character</TYPE>
            <DATATYPE>string</DATATYPE>
            <LENGTH>45</LENGTH>
        </COLUMN>

        <COLUMN name="prix_valeur">
            <PATH syntax="XPath">/pdv_liste/pdv/prix/@valeur</PATH>
            <TYPE>numeric</TYPE>
            <DATATYPE>integer</DATATYPE>
        </COLUMN>

    </TABLE>
</SXLEMAP>';
run;


%macro download();
%do i=2007 %to stopdate-1;      
filename download "folder.&delim.PrixCarburants_annuel_&i..zip";
/* Telechargement du fichier avec la proc HTTP*/
proc http  method='GET'  url="http://donnees.roulez-eco.fr/opendata/annee/i"
 proxyhost=proxyhost proxyport=&proxyport
 out=download;
run;
%end;
filename download "folder.&delim.PrixCarburants_annuel_&stopdate..zip";
/* Telechargement du fichier avec la proc HTTP*/
proc http  method='GET'  url="http://donnees.roulez-eco.fr/opendata/annee"
 proxyhost=proxyhost proxyport=&proxyport  out=download;
run;
%mend download;
/*%download();*/



%macro createtable();
proc datasets library=essence;
   delete pdv prix;
run;
/*%let stop = %sysfunc(year(%sysfunc(today())));*/
%do i=2007 %to stopdate;      
/*--- Declaration du fichier zip avec le filename "zip"---*/
filename inzip zip "folder.&delim.PrixCarburants_annuel_&i..zip";
/*--- data _null_ car il n'y a pas de creation de table SAS a ce stade ---*/
data _null_;
/*--- le infile "inzip" va lire le fichier XML directement dans le zip*/
infile inzip("PrixCarburants_annuel_i..xml");
/*--- déclaration du fichier de sortie*/
file "folder.&delim.PrixCarburants_annuel_&i._final.xml";
/*--- remplissage de l'input buffer*/
input;

/*correction des scories*/
/* Fichier xml 2008 ligne 528841*/
_infile_ = tranwrd(_infile_, "35***", "35000");
/*--- _infile_ est la variable pour acceder au contenu de l input buffer. 
htmldecode remplace la valeur de _infile_ avec la meme valeur dont les balises HTML ont ete converties en caracteres.*/
_infile_ = tranwrd(_infile_, "#x8C;", "OE");
/*_infile_ = tranwrd(_infile_, "#xCODE;","œ");*/
_infile_ = tranwrd(_infile_, "#xC3;&#x89;", "É");
_infile_ = tranwrd(_infile_, "#xC3;&#xA0;", "à");
/*_infile_ = tranwrd(_infile_, 'encoding="ISO-8859-1"', 'encoding="UTF-8"');*/

_infile_ = htmldecode(_infile_);
/*--- ecriture de la ligne convertie vers le fichier de sortie*/
put _infile_;
run;

libname essxml xmlv2 "folder.&delim.PrixCarburants_annuel_&i._final.xml"
xmlmap="folder.&delim.PrixCarburants_annuel_xmlmap.map";

data prix_tmpi/*(drop=prix_maj)*/;
        set essxml.prix;
        format prix_majdate datetime21.2 prix_euros 5.3;
        prix_majdate=input(trim(prix_maj),ymddttm24.);
        prix_euros=trim(prix_valeur/1000);
run;

proc sort data=prix_tmpi;
by pdv_ORDINAL;
run;

data pdv_tmpi;
        set essxml.pdv;
	  taille=1;
        ville=propcase(ville);        
        adresse=propcase(adresse);
        pdv_latitude=pdv_latitude/100000;
        pdv_longitude=pdv_longitude/100000;    
run;

proc sort data=pdv_tmpi;
by pdv_ORDINAL;
run;
proc append base=essence.pdv data=pdv_tmpi FORCE;
run;
proc append base=essence.prix data=prix_tmpi FORCE;
run;

%end;
%mend createtable;
%createtable();

LIBNAME vapublic SASHDAT PATH="/vapublic" 
SERVER = "&vahost" INSTALL = "/opt/TKGrid";

PROC DATASETS LIB=VAPUBLIC;
	delete pdv prix;
run;


data VAPUBLIC.pdv;
	set essence.pdv;
run;

data VAPUBLIC.prix;
	set essence.prix;
run;


proc lasr port=10031
   data=vapublic.pdv
   signer="http://&vahost:7980/SASLASRAuthorization"
    add noclass;
   performance 
      host="&vahost"
      ;
run;

proc lasr port=10031
   data=vapublic.prix
   signer="http://&vahost:7980/SASLASRAuthorization"
    add noclass;
   performance 
      host="&vahost";
run;



LIBNAME LASRLIB SASIOLA  TAG=VAPUBLIC  PORT=10031 HOST="&vahost"  SIGNER="http://&&vahost:7980/SASLASRAuthorization" ;
%vdb_dt(LASRLIB.ESSENCE);

/** LASR STAR SCHEMA CODE **/
proc imstat;
   table LASRLIB.PRIX;
   schema 
      PDV ( pdv_ORDINAL = pdv_ORDINAL
       / prefix = PDV )
   ;
   run;
   table LASRLIB._templast_;
   promote ESSENCE;
   run;
quit;


proc lasr port=10031;
    remove vapublic.prix;
    remove vapublic.pdv;
   	performance 
    host="&vahost";
run;

proc metalib;  
 omr ( library="Visual Analytics Public LASR" REPNAME="Foundation" );
 folder="/Shared Data/SAS Visual Analytics/Public/LASR";
 select ("PDV" "PRIX" "ESSENCE");
 update_rule=(delete);
report;
run;

/* === Nettoyage ===*/
/*

%let folder=/opt/sas/datas/lasradm;

libname essence "folder";

proc datasets library=essence;
   delete pdv prix;
run;


LIBNAME vapublic SASHDAT PATH="/vapublic" 
SERVER = "&vahost" INSTALL = "/opt/TKGrid";


PROC DATASETS LIB=VAPUBLIC;
	delete pdv prix;
run;

proc lasr port=10031;
    remove vapublic.prix;
    remove vapublic.pdv;
   	performance 
    host="&vahost";
run;

LIBNAME LASRLIB SASIOLA  TAG=VAPUBLIC  PORT=10031 HOST="&vahost"  SIGNER="http://&&vahost:7980/SASLASRAuthorization" ;
%vdb_dt(LASRLIB.ESSENCE);

proc metalib;  
 omr ( library="Visual Analytics Public LASR" REPNAME="Foundation" );
 folder="/Shared Data/SAS Visual Analytics/Public/LASR";
 select ("PDV" "PRIX" "ESSENCE");
 update_rule=(delete);
report;
run;
*/



